### ISSUE TITLE
comments are not exported

### ISSUE THREAD

**Issue by mamema** [nateify/amazon-wishlist-exporter#2]
as the topic in question says it:

if wishlist item has comment the json output doesn't have the content

   "comment": null,

**Comment by nateify** [comment]
Can you provide a sample URL or HTML file?

**Comment by mamema** [comment]
nevermind, sorry for the hassle, checked again, now it's working, perhaps same caching issue on amazon side. Great tool btw.

**Comment by nateify** [comment]
I noticed the script continues when Amazon rate limits or doesn't pass captcha and in those cases not all values can be scraped. I introduced retry logic in `0.10.` which should help with this

**Comment by mamema** [comment]
now not every item has a byline value:
eg:
 "items": [
    {
      "asin": "B0018OKAHU",
      "badge": null,
      "byline": null,
      "comment": "test",
      "coupon": null,
      "date-added": null,
      "has": 0,
      "image": "https://m.media-amazon.com/images/I/51Z6WJE5YpL._SS135_.jpg",
      "item-category": "purchasable",
      "item-option": null,
      "link": "https://www.amazon.de/dp/B0018OKAHU/?coliid=IMPHECECRPPM2&colid=1CFRITNNMXGKK&psc=0&ref_=list_c_wl_lv_vv_lig_dp_it",
      "name": "Mannekind (MFSL)",
      "old-price": null,
      "price": null,
      "priority": 0,
      "rating": 3.5,
      "total-ratings": 2,
      "wants": 1
    },

**Comment by nateify** [comment]
This might be this particular item, I don't what would normally be in the byline on that item page. I would still need to see the wishlist URL or HTML to determine.

**Comment by mamema** [comment]
attachted html file, rename to html

[Amazon.txt](https://github.com/user-attachments/files/17798409/Amazon.txt)

**Comment by nateify** [comment]
The byline element is empty in the source for that item, it doesn't have it:
```html
<span id="item-byline-IMPHECECRPPM2" class="a-size-base">
        
    </span>
```
